const LOGIN_SAGA = 'LOGIN_SAGA';
const REGISTER_SAGA = 'REGISTER_SAGA';
const FORGOT_PASSWORD_SAGA = 'FORGOT_PASSWORD_SAGA';
const LOGIN_DISPATCH_REDUCER = 'LOGIN_DISPATCH_REDUCER';

export {
    LOGIN_SAGA,
    REGISTER_SAGA,
    FORGOT_PASSWORD_SAGA,
    LOGIN_DISPATCH_REDUCER
}