const CREATE_COMMENT_SAGA = 'CREATE_COMMENT_SAGA';
const UPDATE_COMMENT_SAGA = 'UPDATE_COMMENT_SAGA';
const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA';

export {
    CREATE_COMMENT_SAGA,
    UPDATE_COMMENT_SAGA,
    DELETE_COMMENT_SAGA,
}