const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
const DUPPLICATE_PROJECT_NAME = 'DUPPLICATE_PROJECT_NAME';
const GET_ALL_PROJECTS_SAGA = 'GET_ALL_PROJECTS_SAGA';
const GET_ALL_PROJECTS_DISPATCH = 'GET_ALL_PROJECTS_DISPATCH';
const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';
const UPDATE_PORJECT_SAGA = 'UPDATE_PORJECT_SAGA';
const DELETE_PORJECT_SAGA = 'DELETE_PORJECT_SAGA';
const ADD_MEMBER_TO_PROJECT_SAGA = 'ADD_MEMBER_TO_PROJECT_SAGA';
const DELETE_MEMBER_FROM_PROJECT_SAGA = 'DELETE_MEMBER_FROM_PROJECT_SAGA';
const GET_PROJECT_BOARD_SAGA = 'GET_PROJECT_BOARD_SAGA';
const GET_LIST_MEMBERS_SAGA = 'GET_LIST_MEMBERS_SAGA';


export {
    CREATE_PROJECT_SAGA,
    DUPPLICATE_PROJECT_NAME,
    GET_ALL_PROJECTS_SAGA,
    GET_ALL_PROJECTS_DISPATCH,
    GET_PROJECT_DETAIL_SAGA,
    UPDATE_PORJECT_SAGA,
    DELETE_PORJECT_SAGA,
    ADD_MEMBER_TO_PROJECT_SAGA,
    DELETE_MEMBER_FROM_PROJECT_SAGA,
    GET_PROJECT_BOARD_SAGA,
    GET_LIST_MEMBERS_SAGA,
}