const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
const DUPPLICATE_PROJECT_NAME = 'DUPPLICATE_PROJECT_NAME';
const GET_ALL_PROJECTS_SAGA = 'GET_ALL_PROJECTS_SAGA';
const GET_ALL_PROJECTS_DISPATCH = 'GET_ALL_PROJECTS_DISPATCH';
const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';

export {
    CREATE_PROJECT_SAGA,
    DUPPLICATE_PROJECT_NAME,
    GET_ALL_PROJECTS_SAGA,
    GET_ALL_PROJECTS_DISPATCH,
    GET_PROJECT_DETAIL_SAGA
}