const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA';
const GET_ALL_PROJECT_CATEGORY_DISPATCH_REDUCER = 'GET_ALL_PROJECT_CATEGORY_DISPATCH_REDUCER';

export {
    GET_ALL_PROJECT_CATEGORY_SAGA,
    GET_ALL_PROJECT_CATEGORY_DISPATCH_REDUCER
}