const SHOW_CREATE_TASK_MODAL_SAGA = 'SHOW_CREATE_TASK_MODAL_SAGA';
const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA';
const GET_ALL_TASKS_BY_PROJECT_SAGA = 'GET_ALL_TASKS_BY_PROJECT_SAGA';
const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA';
const UPDATE_TASK_STATUS_SAGA = 'UPDATE_TASK_STATUS_SAGA';

export {
    SHOW_CREATE_TASK_MODAL_SAGA,
    CREATE_TASK_SAGA,
    GET_ALL_TASKS_BY_PROJECT_SAGA,
    GET_TASK_DETAIL_SAGA,
    UPDATE_TASK_SAGA,
    UPDATE_TASK_STATUS_SAGA,
}