const SEARCH_USER_SAGA = 'SEARCH_USER_SAGA';
const DISPATCH_USERS_SEARCHED_ON_REDUCER = 'DISPATCH_USERS_SEARCHED_ON_REDUCER';
const UPDATE_USER_SAGA = 'UPDATE_USER_SAGA';
const UPLOAD_AVATAR_USER_SAGA = 'UPLOAD_AVATAR_USER_SAGA';

export {
    SEARCH_USER_SAGA,
    DISPATCH_USERS_SEARCHED_ON_REDUCER,
    UPDATE_USER_SAGA,
    UPLOAD_AVATAR_USER_SAGA,
}